# Don't change the volume names without also changing them in up.sh
volumes:

  # Going to be filled with the contents of the
  #       ./shared_data/
  # folder.
  shared_data:

  # Going to be filled with the workspace built by
  #       ../colcon_workspace_builder/
  # folder.
  colcon_workspace:

services:

  # this container primes the shared volumes and allows the content to be place in them
  init:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    volumes:
      - shared_data:/etc/docker/shared_data:consistent
      - colcon_workspace:/etc/docker/colcon_workspace:consistent

  # zenoh router
  zenoh:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    env_file:
      - ./stack.env
    command: bash -c "export ZENOH_ROUTER_CONFIG_URI=`ros2 pkg prefix mrs_uav_deployment`/share/mrs_uav_deployment/config/zenoh/uav_router.json5; ros2 run rmw_zenoh_cpp rmw_zenohd"

  # starts a custom node from your colcon_workspace
  custom_node:
    image: valseb:5000/ctumrs/mrs_uav_system:valentin
    network_mode: host
    volumes:
      - /dev:/dev
      - shared_data:/etc/docker/shared_data
      - colcon_workspace:/etc/docker/colcon_workspace
    privileged: true
    env_file:
      - ./stack.env
    command: >
      bash -c "source /etc/docker/colcon_workspace/install/setup.bash && ros2 launch mrs_octomap_server octomap.launch.py use_sim_time:=false lidar_3d_topic_0_in:=/uav27/ouster/points"

  # starts the HW API for connecting the MRS UAV System to PX4
  ouster:
    image: valseb:5000/ctumrs/mrs_uav_system:valentin
    network_mode: host
    volumes:
      - /dev:/dev
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "ros2 launch ouster_ros sensor.composite.launch.py sensor_hostname:=10.10.20.90 udp_dest:=10.10.20.127 viz:=false"

  bluefox_imu:
    image: ctumrs/mrs_uav_system:stable
    network_mode: host
    volumes:
      - /dev/:/dev/ # besides setting 'privileged' flag to true, you also have to mount '/dev' to see device file
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "ros2 launch mrs_serial vio_imu.launch.py"

#  bluefox:
#    image: ctumrs/bluefox2:stable # ctumrs/mrs_uav_system is not used here, because bluefox2 is not multiplatform
#    network_mode: host
#    volumes:
#      - /dev/:/dev/
#    privileged: true
#    env_file:
#      - ./stack.env
    # there is no command, because launch command is a part of the entrypoint

#  vio:
#    image: ctumrs/bluefox2:stable
#    network_mode: host
#    volumes:
#      - /dev/:/dev/
#    privileged: true
#    env_file:
#      - ./stack.env
#    entrypoint: [
#      "bash", "-c",
#      "source /opt/ros/jazzy/setup.sh && ros2 launch mrs_open_vins_core open_vins.launch.py"
#    ]

  # starts the HW API for connecting the MRS UAV System to PX4
  hw_api:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    volumes:
      - /dev:/dev
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "ros2 launch mrs_uav_px4_api api.launch.py"

  # starts the MRS UAV System's core
  uav_core:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    volumes:
      - shared_data:/etc/docker/shared_data
    env_file:
      - ./stack.env
    command: bash -c "ros2 launch mrs_uav_core core.launch.py platform_config:=`ros2 pkg prefix mrs_uav_deployment`/share/mrs_uav_deployment/config/mrs_uav_system/${UAV_TYPE}.yaml world_config:=`ros2 pkg prefix mrs_uav_deployment`/share/mrs_uav_deployment/config/worlds/world_${WORLD_NAME}.yaml custom_config:=/etc/docker/shared_data/custom_config.yaml network_config:=/etc/docker/shared_data/network_config.yaml"

  # automatic initialization of the system and takeoff
  automatic_start:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    #volumes:
    #  - shared_data:/etc/docker/shared_data
    env_file:
      - ./stack.env
    # custom_config:=/etc/docker/shared_data/automatic_start.yaml
    command: bash -c "ros2 launch mrs_uav_autostart automatic_start.launch.py"

  static_tfs:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    volumes:
      - /dev:/dev
      - shared_data:/etc/docker/shared_data:consistent
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "/etc/docker/shared_data/static_tfs.sh"

  # `rosbag record`
  # - wayForOffboard will unblock during takeoff
  # - the rosbags are going to be placed in
  #       /home/mrs/docker/${SESSION_NAME}/bag_files
  rosbag:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - DRONE_USER_NAME=${DRONE_USER_NAME}
    volumes:
      - shared_data:/etc/docker/shared_data
      - /home/${DRONE_USER_NAME}/docker/${SESSION_NAME}/bag_files:/etc/docker/bag_files:consistent
    env_file:
      - ./stack.env
    command: bash -c "/etc/docker/shared_data/record.sh /etc/docker/bag_files"

  # logging of all the docker containers within this session
  # - the logs are going to be placed in
  #       /home/mrs/docker/${SESSION_NAME}/logs
  dogtail:
    image: klaxalk/dogtail:latest
    environment:
      - SESSION_NAME=${SESSION_NAME}
      - DRONE_USER_NAME=${DRONE_USER_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${DRONE_USER_NAME}/docker/${SESSION_NAME}/logs:/etc/logs:consistent
